import Head from "next/head";
import type {GetServerSideProps} from "next";
import {useState,type FormEvent} from "react";
import {proposalConfirmationSecret,verifyProposalConfirmationToken} from "@/server/proposal-confirmation";

type Props={valid:boolean;error?:string;token?:string;proposal?:{proposalCode:string;status:string;total:number;currencyCode:string;customerName:string;siteAddress:string;lineCount:number}};
const money=(n:number,currency:string)=>new Intl.NumberFormat("en-AU",{style:"currency",currency,maximumFractionDigits:0}).format(n);

export default function ConfirmProposal({valid,error,token,proposal}:Props){
  const [name,setName]=useState(proposal?.customerName||""),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[result,setResult]=useState<{ok:boolean;message:string}|null>(proposal?.status==="ACCEPTED"?{ok:true,message:"This Proposal has already been confirmed."}:null);
  async function submit(event:FormEvent){event.preventDefault();setBusy(true);setResult(null);const response=await fetch("/api/proposals/customer-confirm",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token,acceptedByName:name,confirmed})});const body=await response.json();if(response.ok)setResult({ok:true,message:"Thank you. Your Better Home Proposal is confirmed."});else setResult({ok:false,message:body.error==="CONFIRMATION_LINK_EXPIRED"?"This confirmation link has expired. Please reply to your Better Home email for a fresh link.":"We could not record your confirmation. Please reply to your Better Home email and we will help."});setBusy(false);}
  if(!valid||!proposal)return <main className="customer-confirm"><section><img src="https://www.bhtechnology.com.au/better-home-header-logo.png" alt="Better Home"/><p>PROPOSAL CONFIRMATION</p><h1>This link is no longer available.</h1><span>{error==="CONFIRMATION_LINK_EXPIRED"?"Please reply to your Better Home email for a fresh confirmation link.":"Please contact your Better Home representative for assistance."}</span></section></main>;
  return <><Head><title>Confirm {proposal.proposalCode} — Better Home</title><meta name="robots" content="noindex,nofollow"/></Head><main className="customer-confirm"><section><img src="https://www.bhtechnology.com.au/better-home-header-logo.png" alt="Better Home"/><p>YOUR BETTER HOME PROPOSAL</p><h1>One clear decision.</h1><span>Review the fixed proposal reference and investment below. Confirmation records your approval of this exact version; it does not process a payment.</span><dl><div><dt>Proposal</dt><dd>{proposal.proposalCode}</dd></div><div><dt>Property</dt><dd>{proposal.siteAddress}</dd></div><div><dt>Selected scope</dt><dd>{proposal.lineCount} items</dd></div><div className="confirm-total"><dt>Investment</dt><dd>{money(proposal.total,proposal.currencyCode)}</dd></div></dl>{result?.ok?<div className="confirm-success"><b>Confirmed</b><h2>{result.message}</h2><p>Your Better Home representative can now prepare the next steps with you.</p></div>:<form onSubmit={submit}><label>Your full name<input value={name} onChange={e=>setName(e.target.value)} required/></label><label className="confirm-check"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><span>I confirm Proposal {proposal.proposalCode} for {money(proposal.total,proposal.currencyCode)} and ask Better Home to prepare the next step.</span></label>{result&&!result.ok?<strong>{result.message}</strong>:null}<button disabled={busy||!confirmed||!name.trim()}>{busy?"Confirming…":"Confirm this Proposal"}</button><small>No payment is taken here. Site conditions and the formal agreement remain subject to the recorded Proposal terms.</small></form>}<footer>Technology should quietly support everyday life.</footer></section></main></>;
}

export const getServerSideProps:GetServerSideProps<Props>=async context=>{
  const token=String(context.query.token||"");let claim;try{claim=verifyProposalConfirmationToken(token,proposalConfirmationSecret());}catch(error){return {props:{valid:false,error:error instanceof Error?error.message:"INVALID_CONFIRMATION_LINK"}};}
  const {readContext}=require("@bht/product-os/v2");const os=readContext.createProductOsV2ReadContext();
  try{const proposal=await os.prisma.pos2Proposal.findUnique({where:{proposalCode:claim.proposalCode},include:{draftVersion:{include:{draft:true,lines:true}}}});if(!proposal||proposal.selectionFingerprint!==claim.fingerprint||String(proposal.draftVersion.draft.customerEmail||"").trim().toLowerCase()!==claim.customerEmail)return {props:{valid:false,error:"CONFIRMATION_LINK_DOES_NOT_MATCH"}};return {props:{valid:true,token,proposal:{proposalCode:proposal.proposalCode,status:proposal.status,total:Number(proposal.total),currencyCode:proposal.currencyCode,customerName:proposal.draftVersion.draft.customerName||"",siteAddress:proposal.draftVersion.draft.siteAddress||"Address to be confirmed",lineCount:proposal.draftVersion.lines.length}}};}finally{await os.disconnect();}
};
