const test=require("node:test");
const assert=require("node:assert/strict");
const {assembleProductReadModel}=require("../../src/v2/product-read-service");
const {toPrintProductSheet}=require("../../src/v2/product-read-model");
const {calculateSelectionQuote}=require("../../src/v2/selection-quote");

function placement(kind,body,surface,side="BACK",sortOrder=1,title=null){return {surface,side,sortOrder,status:"ACTIVE",contentEntry:{contentKey:`${surface}.${kind}`,contentKind:kind,title,body}}}
function product(overrides={}){return {id:"p1",productCode:"C-02",canonicalName:"Living Collection",productKind:"COLLECTION",commercialRole:"STANDARD",requiresFoundation:true,parent:null,versions:[{versionLabel:"V2.07"}],prices:[{priceCode:"p",amount:2999,currencyCode:"AUD",displayMode:"EXACT",taxBasis:"GST_INCLUSIVE",fulfilmentMode:"INSTALLED",installationIncluded:true}],contentPlacements:[placement("HERO","One space.","front.hero","FRONT"),placement("PROBLEM","One room holds many moments.","back.problem"),placement("CUSTOMER_EXPERIENCE_COPY","Light arrives with you.","back.experience.1","BACK",1,"A QUIET WELCOME"),placement("CUSTOMER_EXPERIENCE_COPY","Up to 6 lighting circuits\n1 room switch","back.scope.1","BACK",1,"ROOM LIGHT")],experiences:[],capabilityInclusions:[],relationshipsFrom:[],installationAssumptions:[],imageLinks:[{asset:{assetCode:"hero",storageUri:"/hero.jpg",altTextDefault:"Living",publishStatus:"APPROVED"},crop:null}],themes:[],layoutConfigs:[],includedBenefits:[],featuredAsParent:[],...overrides}}

test("one assembled model feeds website and A4 print without a second content source",()=>{const m=assembleProductReadModel(product());assert.equal(m.hero,"One space.");assert.equal(m.customerExperiences[0].title,"A QUIET WELCOME");assert.deepEqual(m.standardScope[0].lines,["Up to 6 lighting circuits","1 room switch"]);assert.equal(m.printEligible,true);assert.equal(toPrintProductSheet(m).product,m)});
test("unapproved image keeps data readable but blocks formal print",()=>{const p=product({imageLinks:[{asset:{assetCode:"hero",storageUri:"/placeholder.jpg",publishStatus:"NOT_APPROVED_FOR_PUBLISH"},crop:null}]});const m=assembleProductReadModel(p);assert.equal(m.approvedImage,null);assert.equal(m.printEligible,false);assert.throws(()=>toPrintProductSheet(m),/not print-eligible/)});
test("quote projection uses the same active price and enforces Foundation",()=>{const m=assembleProductReadModel(product());const blocked=calculateSelectionQuote([{product:m,quantity:2}]);assert.equal(blocked.valid,false);assert.equal(blocked.total,5998);const ok=calculateSelectionQuote([{product:m,quantity:2}],{foundationSelected:true});assert.equal(ok.valid,true);assert.equal(ok.total,5998)});
