import Head from "next/head";
import type { GetServerSideProps } from "next";
import {useState} from "react";

type Line={productCode:string;productName:string;quantity:number;unitPrice:number;lineTotal:number};
type Version={versionNumber:number;total:number;currencyCode:string;taxBasis:string;createdAt:string;lines:Line[];proposals:{proposalCode:string;status:string;total:number;createdAt:string}[]};
type Draft={draftCode:string;status:string;customerName:string|null;customerEmail:string|null;customerPhone:string|null;siteAddress:string|null;currentVersion:number;updatedAt:string;owner:{displayName:string;email:string}|null;customerLink:{status:string;crmContactId:string|null;crmOpportunityId:string|null}|null;versions:Version[];latest:Version|null};
type Props={locked?:boolean;notFound?:boolean;draft?:Draft};
type CrmContext={opportunity_id:string;stage:string;account_name:string|null;contact_name:string|null;email:string|null;phone:string|null;asset_name:string|null;asset_address:string|null;eligible:boolean;missing:string[]};
const money=(n:number)=>new Intl.NumberFormat("en-AU",{style:"currency",currency:"AUD",maximumFractionDigits:0}).format(n);
const date=(value:string)=>new Intl.DateTimeFormat("en-AU",{day:"numeric",month:"short",year:"numeric",hour:"numeric",minute:"2-digit"}).format(new Date(value));

export default function DraftDetail({locked,notFound,draft}:Props){
  const [status,setStatus]=useState(draft?.status||"");const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);const [createdProposal,setCreatedProposal]=useState("");const [crmQuery,setCrmQuery]=useState("");const [crmResults,setCrmResults]=useState<CrmContext[]>([]);const [crmMessage,setCrmMessage]=useState("");const [crmConfirmed,setCrmConfirmed]=useState(draft?.customerLink?.status==="CONFIRMED");
  if(locked||notFound||!draft)return <main className="sales-locked"><div><p>BETTER HOME</p><h1>{notFound?"Draft not found.":"Sales Studio"}</h1><span>{notFound?"This selection may have moved or the reference is incorrect.":"Internal access is not configured on this environment."}</span><a href="/sales">Return to Sales Studio</a></div></main>;
  const latest=draft.latest!;
  const transition=async(kind:"ready"|"proposals")=>{setBusy(true);setMessage(kind==="ready"?"Preparing for review…":"Creating proposal from this version…");try{const response=await fetch(`/api/drafts/${encodeURIComponent(draft.draftCode)}/${kind}`,{method:"POST"});const result=await response.json();if(!response.ok)throw new Error(result.error);if(kind==="ready"){setStatus("READY_FOR_REVIEW");setMessage("Ready for review. This Draft can now become a Proposal.");}else{setStatus("CONVERTED");setCreatedProposal(result.proposalCode);setMessage(`${result.proposalCode} created from version ${result.draftVersion}.`);}}catch(error){setMessage(error instanceof Error?error.message:"The action could not be completed.");}finally{setBusy(false);}};
  const searchCrm=async()=>{setCrmMessage("Searching eligible Better Home opportunities…");try{const response=await fetch(`/api/crm-context/search?draftCode=${encodeURIComponent(draft.draftCode)}&q=${encodeURIComponent(crmQuery)}`);const result=await response.json();if(!response.ok)throw new Error(result.error);setCrmResults(result.results||[]);setCrmMessage(result.results?.length?"Review the complete customer context before linking.":"No eligible Better Home Opportunity found. Prepare the Opportunity in CRM first.");}catch(error){setCrmMessage(error instanceof Error?error.message:"CRM search failed");}};
  const confirmCrm=async(opportunityId:string)=>{setBusy(true);setCrmMessage("Confirming this customer relationship…");try{const response=await fetch(`/api/drafts/${encodeURIComponent(draft.draftCode)}/crm-link`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({opportunityId})});const result=await response.json();if(!response.ok)throw new Error(result.error);setCrmConfirmed(true);setCrmResults([]);setCrmMessage("CRM customer, account, property and Opportunity confirmed.");}catch(error){setCrmMessage(error instanceof Error?error.message:"CRM link could not be confirmed");}finally{setBusy(false);}};
  return <><Head><title>{draft.draftCode} — Sales Studio</title><meta name="robots" content="noindex,nofollow"/></Head><main className="sales-detail">
    <nav><a href="/sales">← Sales Studio</a><span>BETTER HOME</span></nav>
    <header><div><p>SELECTION DRAFT · VERSION {draft.currentVersion}</p><h1>{draft.customerName||"Unnamed customer"}</h1><span>{draft.siteAddress||draft.customerEmail||"Customer details pending"}</span></div><div><small>{status.replaceAll("_"," ")}</small><strong>{money(latest.total)}</strong><a href={`/configure?draft=${encodeURIComponent(draft.draftCode)}`}>Continue editing</a></div></header>
    <section className="sales-detail-grid"><article><p>CUSTOMER</p><dl><div><dt>Email</dt><dd>{draft.customerEmail||"—"}</dd></div><div><dt>Phone</dt><dd>{draft.customerPhone||"—"}</dd></div><div><dt>Site</dt><dd>{draft.siteAddress||"—"}</dd></div><div><dt>CRM link</dt><dd>{draft.customerLink?.status||"REVIEW REQUIRED"}</dd></div></dl></article><article><p>OWNERSHIP</p><dl><div><dt>Owner</dt><dd>{draft.owner?.displayName||"—"}</dd></div><div><dt>Email</dt><dd>{draft.owner?.email||"—"}</dd></div><div><dt>Updated</dt><dd>{date(draft.updatedAt)}</dd></div><div><dt>Reference</dt><dd>{draft.draftCode}</dd></div></dl></article></section>
    {!crmConfirmed&&<section className="sales-crm-context"><div><p>CRM CONTEXT</p><h2>Find the complete customer relationship.</h2><span>Only Opportunities assigned to the Better Home Proposal channel are shown.</span></div><div className="sales-crm-search"><input value={crmQuery} onChange={e=>setCrmQuery(e.target.value)} placeholder="Name, email, phone or property"/><button disabled={busy} onClick={searchCrm}>Search CRM</button></div>{crmMessage&&<p className="sales-crm-message">{crmMessage}</p>}{crmResults.map(x=><article key={x.opportunity_id}><div><b>{x.contact_name||"Contact pending"}</b><span>{x.account_name||"Account pending"} · {x.asset_address||x.asset_name||"Property pending"}</span></div><div><small>OPPORTUNITY</small><span>{x.stage} · {x.opportunity_id}</span></div>{x.eligible?<button disabled={busy} onClick={()=>confirmCrm(x.opportunity_id)}>Confirm link</button>:<strong>{`Missing ${x.missing.join(", ")}`}</strong>}</article>)}</section>}
    {crmConfirmed&&crmMessage&&<section className="sales-crm-confirmed"><p>CRM CONTEXT</p><strong>{crmMessage}</strong></section>}
    <section className="sales-detail-lines"><div><p>LATEST SELECTION</p><h2>What belongs in this home.</h2></div>{latest.lines.map(line=><article key={line.productCode}><div><small>{line.productCode}</small><b>{line.productName}</b></div><span>{line.quantity} × {money(line.unitPrice)}</span><strong>{money(line.lineTotal)}</strong></article>)}<footer><span>Indicative total<br/><small>{latest.taxBasis.replaceAll("_"," ")} · {latest.currencyCode}</small></span><strong>{money(latest.total)}</strong></footer></section>
    <section className="sales-decision"><div><p>DECISION</p><h2>{status==="DRAFT"?"Ready for an internal check?":status==="READY_FOR_REVIEW"?"Create a fixed Proposal.":"This Draft has become a Proposal."}</h2><span>{status==="DRAFT"?"Marking it ready does not send anything to the customer.":status==="READY_FOR_REVIEW"?`The Proposal will be locked to version ${draft.currentVersion}.`:"Further changes should begin as a new Draft version."}</span></div>{status==="DRAFT"?<button disabled={busy} onClick={()=>transition("ready")}>Mark ready for review</button>:status==="READY_FOR_REVIEW"?<button disabled={busy} onClick={()=>transition("proposals")}>Create Proposal</button>:createdProposal?<a href={`/sales/proposals/${createdProposal}`}>Open Proposal</a>:null}{message&&<p className="sales-decision-message">{message}</p>}</section>
    <section className="sales-history"><p>VERSION HISTORY</p>{draft.versions.map(v=><article key={v.versionNumber}><b>Version {v.versionNumber}</b><span>{date(v.createdAt)} · {v.lines.length} selections{v.proposals.map(p=><a key={p.proposalCode} href={`/sales/proposals/${p.proposalCode}`}> · {p.proposalCode}</a>)}</span><strong>{money(v.total)}</strong></article>)}</section>
  </main></>;
}

export const getServerSideProps:GetServerSideProps<Props>=async context=>{
  const {actorFromRequest}=await import("@/server/sales-auth");const actor=actorFromRequest(context.req);if(!actor)return {redirect:{destination:`/login?next=${encodeURIComponent(context.resolvedUrl)}`,permanent:false}};
  const {readContext,salesStudioService}=require("@bht/product-os/v2");const os=readContext.createProductOsV2ReadContext();
  try{const draft=await salesStudioService.createSalesStudioService(os.prisma).draftDetail(actor,String(context.params?.draftCode||""));if(!draft)return {props:{notFound:true}};return {props:{draft:JSON.parse(JSON.stringify(draft))}};}finally{await os.disconnect();}
};
