import Head from "next/head";
import type {FormEvent} from "react";
import {useState} from "react";
import type {GetServerSideProps} from "next";
import PasswordField from "@/components/PasswordField";

export default function ChangePassword({required}:{required:boolean}){const [error,setError]=useState("");const [busy,setBusy]=useState(false);async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const data=new FormData(event.currentTarget),next=String(data.get("newPassword")||""),confirm=String(data.get("confirmPassword")||"");if(next!==confirm){setError("The new passwords do not match.");setBusy(false);return;}const response=await fetch("/api/auth/change-password",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({currentPassword:data.get("currentPassword"),newPassword:next})});if(response.ok)window.location.assign("/sales");else{const result=await response.json();setError(result.error==="CURRENT_PASSWORD_INVALID"?"The current password is incorrect.":"Use at least 12 characters and choose a different password.");setBusy(false);}}return <><Head><title>Change password — Better Home</title><meta name="robots" content="noindex,nofollow"/></Head><main className="sales-login"><section><p>BETTER HOME</p><h1>{required?"Choose your password.":"Change your password."}</h1><span>{required?"Replace the temporary password before entering Sales Studio.":"Keep your Sales Studio account secure."}</span><form onSubmit={submit}><label>{required?"Temporary password":"Current password"}<PasswordField name="currentPassword" autoComplete="current-password" required autoFocus/></label><label>New password<PasswordField name="newPassword" autoComplete="new-password" minLength={12} required/></label><label>Confirm new password<PasswordField name="confirmPassword" autoComplete="new-password" minLength={12} required/></label>{error&&<strong>{error}</strong>}<button disabled={busy}>{busy?"Saving…":"Save and continue"}</button></form><small>Use at least 12 characters. A password manager is recommended.</small></section></main></>}

export const getServerSideProps:GetServerSideProps=async context=>{const {actorFromRequest}=await import("@/server/sales-auth");const actor=actorFromRequest(context.req);if(!actor)return {redirect:{destination:"/login",permanent:false}};return {props:{required:Boolean(actor.mustChangePassword)}};};
