import Head from "next/head";
import Link from "next/link";
import type {GetServerSideProps} from "next";

type Customer={contact_id:string;name:string|null;email:string|null;phone:string|null;account_id:string|null;account_name:string|null;updated_at:string|null};
type Props={customers:Customer[]};

export default function Customers({customers}:Props){return <><Head><title>Customers — Better Home Sales Studio</title><meta name="robots" content="noindex,nofollow"/></Head><main className="sales-shell"><aside className="sales-nav"><Link href="/sales" className="sales-brand">BETTER HOME</Link><p>SALES STUDIO</p><nav><Link href="/sales">Overview</Link><Link href="/configure" prefetch>New selection</Link><Link className="active" href="/sales/customers">Customers</Link><Link href="/sales/proposals">Proposals</Link></nav></aside><section className="sales-main"><header><div><p>CUSTOMERS</p><h1>People and homes.</h1><span>Recent CRM contacts available to Better Home sales.</span></div><Link href="/configure" prefetch>Start a selection</Link></header><section className="sales-list sales-customers"><div className="sales-list-head"><div><p>CRM DIRECTORY</p><h2>Recent customers</h2></div></div>{customers.length?<div className="sales-table">{customers.map(customer=><article key={customer.contact_id}><div><b>{customer.name||"Unnamed contact"}</b><span>{customer.account_name||"No account"}</span></div><div><small>EMAIL</small><span>{customer.email||"—"}</span></div><div><small>PHONE</small><span>{customer.phone||"—"}</span></div><strong>{customer.updated_at?new Date(customer.updated_at).toLocaleDateString("en-AU"):"—"}</strong><Link className="sales-open" href={`/configure?customer=${encodeURIComponent(customer.contact_id)}`}>Select</Link></article>)}</div>:<div className="sales-empty"><h3>No CRM customers found.</h3><p>New customers can still begin from a fresh selection.</p></div>}</section></section></main></>}

export const getServerSideProps:GetServerSideProps<Props>=async context=>{const {actorFromRequest}=await import("@/server/sales-auth");const actor=actorFromRequest(context.req);if(!actor)return {redirect:{destination:"/login?next=%2Fsales%2Fcustomers",permanent:false}};const {readContext,salesStudioService}=require("@bht/product-os/v2");const os=readContext.createProductOsV2ReadContext();try{return {props:{customers:JSON.parse(JSON.stringify(await salesStudioService.createSalesStudioService(os.prisma).customers(actor)))}};}finally{await os.disconnect();}};
